### PR TITLE
make the starting positions of the mouse paw customizable

### PR DESCRIPTION
**Pull request by peeteer1245**
* also added missing config options to config

Made the starting positions of the mouse paw
customizable by adding new config options.

This applies to the osu and custom mode.

Comparison of the default coordinates
with some arbitrary coordinates:
comparison

### CODE REVIEW

**Comment by erichyang** [comment]
hey @peeteer1245, your work looks awesome here. Would you be so kind as to compile a build for me that includes your work on both on #98 and #88? Thank you!

**Comment by peeteer1245** [comment]
Sure thing @erichyang.
Regarding #88 I published a release on my fork [here](https://github.com/peeteer1245/bongocat-osu/releases/tag/v1.5.2).
With #98 there really was nothing I did except for cross-compiling since the participants did not have a up to date build.

**Comment by kuroni** [comment]
Nice. Can you add a PR to the wiki as well or only I have the access to the wiki?

**Comment by peeteer1245** [comment]
Since the Wiki is a separate repo without PR functionality I cannot create a PR.
But you can use the information in [this gist](https://gist.github.com/larrybotha/10650410#merging-changes) to merge my changes.
My Wiki FREPO is https://github.com/peeteer1245/bongocat-osu.wiki.git.

**Review by sabroso23 — COMMENTED** [review]
bongo Cat is cool

**Comment by sseelleb** [comment]
@peeteer1245 so sorry to bother u, but ive been having a hard time finding out what are the coordinates i need for my image, may i know how to do so?

**Comment by peeteer1245** [comment]
I'm not sure if the config file included in the download is up to date.

If it is the there should be a couple of coordinates the far bottom of it. You will have to play with them to get it just right.

If it is not you will have to add some lines to the bottom of your config file. [Here](https://github.com/kuroni/bongocat-osu/blob/111bebdc31c2c16941fba272bac612d339dc795a/src/data.cpp#L75) are the default configurations. The specific point I linked has the info for the mouse-paw-coordinates.

If you have problems modifying your config file you can attach it in a comment and I can help you with it.

**Pull request merged**
